### ISSUE TITLE
commandline support

### ISSUE THREAD

**Issue by archy-embedinn** [n7tae/mvoice#10]
Hi, 
Can I use the mvoice without GUI?
is there any way I can pipe the audio to mvoice and it sends over udp to specified ip:port
on the reciever side i can receive using mvoice and pipe to aplay. I hope you have done it in the initial development of this project, it would be great if you can share this.

What I am trying is from codec2:
Tx side
./src/c2enc 3200 ../wav/all.wav - | [mvoice to udp sink]
Rx side:
[mvoice to udp source] | ./src/c2dec 3200 - - | aplay -f S16_LE

This will be very simple to send encoded voice over point to point ethernet link

**Comment by n7tae** [comment]
Sorry, mvoice was never without a GUI in any stage of its development.
