### ISSUE TITLE
g++: fatal error: Killed signal terminated program cc1plus

### ISSUE THREAD

**Issue by kd8bxp** [n7tae/mvoice#12]
I have a rPI 3B which I am trying (have been trying) to get mvoice to compile and install.
I am running buster 2020-02-13 version.
My PI seems to be running very slowly, but I'm not sure that is the problem
I keep getting the above error after a few hours of waiting....

I've been at it most of the day - so many hours of waiting really.
But will this compile on the older hardware ?  If so, what do I need to do to get it to compile?

Thanks

**Comment by n7tae** [comment]
Googling on your error message, this is a known problem with the RPi and is caused by the Pi running out of memory. I have a 3B rev 1.2 and have compiled it on 32-bit buster without any problems. I have also compiled it on 64-bit bullseye. In this case, "make" works but "make -j4" doesn't. If you are using the -j option, try it without.
If you have programs that are running and use a lot of memory, uninstall them. Or even better, start with a fresh image. I recommend sticking with the 32-bit version on a model 3, even though it will run 64-bit.
Some google solutions point to creating a swap file, but I haven't tried this.

**Comment by kd8bxp** [comment]
Thank you, 
I did do a clean install after, so I think I probably downloaded the wrong image for the PI. It's very slow, and I don't recall this PI being slow before.
I also should have said that I googled the problem and came up with memory being a possible cause. Being that it was a clean install I wasn't sure that was my issue. It seems your google results are better then mine. And I didn't consider 64-bit vs 32-bit.... 
However "getconf LONG_BIT" says I am using a 32-bit system. 

I'm very confused. But will keep trying perhaps I need to try on a different PI maybe the one I have is damaged some how.
Thanks for the info, thanks for the project. I'll keep trying.

**Comment by n7tae** [comment]
Sorry you're having this trouble. mvoice is not a big program, code-wise, but gtk++ is. I need to change the gui. I don't really like gtk++, but it was the easiest to implement and at the time, and I was trying to get an M17 client working quickly. I had just created mrefd and there were no clients to connect to it!
Your pi might be okay, maybe the power supply is going bad. I've had that experience. You might want to also consider the Pi OS (Legacy). It might do better.
I'm not a fan of the Raspberry Pis, but I suppose you get what you pay for. There a many SBCs that are better, but they all cost more.

**Comment by kd8bxp** [comment]
I thought of power supply already, and tried a different one.
Too be fair it's been over a year since I used this PI.... I also broke the first rule for using a PI and tried to update it (My rule has been once you get the things working leave them alone. Now I remember why that was a rule of mine :-) )
Just knowing that it will compile with a 3B means (at least to me) that I either have a bad PI or I am doing something wrong. 
The speed of the PI is kind of telling me I have a problem.  
I will try a different SD card, it's likely that has become corrupted over time and is just not as fast as it use to be.

I like the price of the PIs, but the 4B+ is really the one to get if you can find them. (Every thing else about them is kind of frustrating and working with the older hardware is really frustrating at best.) 
Anyway, seems like it's an issue on my side of things.
Thanks again for the help and info.

**Comment by kd8bxp** [comment]
Update: Looks like the configuration for the touch screen I have hooked up was (or is) causing the slow down issues, removed it, and the configuration files for it. And the rPI 3B is pretty zippy.... Looks like "Buster" doesn't like something about the screen.
I'm going to dig into that a bit more. But looks like this was my issue.
Thanks again for the help. 
73 de KD8BXP
