### ISSUE TITLE
Transparent title bar

### ISSUE THREAD

**Issue by sp5wwp** [n7tae/mvoice#2]
System: Ubuntu 18.04.5 LTS

![image](https://user-images.githubusercontent.com/44336093/96348092-75172a00-10a6-11eb-9a4a-e7a56e8cad64.png)

**Comment by n7tae** [comment]
Interesting. I don't see this on Ubuntu 20.4. According to glade, my design tool, the opacity of both the window and the menu bar are both set to 1.00. How do the About and Settings dialogw look?

**Comment by sp5wwp** [comment]
![image](https://user-images.githubusercontent.com/44336093/96361837-7178b700-1129-11eb-9d2f-f03d9d71384d.png)
![image](https://user-images.githubusercontent.com/44336093/96361851-835a5a00-1129-11eb-91a1-61e2f7cd8ee7.png)

**Comment by n7tae** [comment]
Fixed. I was doing something stupid with glade.
