### ISSUE TITLE
CODEC Issue

### ISSUE THREAD

**Issue by TemporarilyOffline** [n7tae/mvoice#20]
During our live stream playing with the software: https://youtube.com/live/okioT5H_jN8 (we didn't know what we were doing going in, that's the show's premise) we uncovered an issue (and forgive me because this was while live streaming which is hectic).

I switched to the 1600 voice+data codec and my transmission was heard on the remote end, but I could not decode return traffic.  

Return traffic was from droidstar and users were able to hear me, but they couldn't change their codec.  They sent back a transmission at 3200 voice only (I think its 3200, but you get the idea) and I could not hear them.

Possible solution: Detect incoming codec and switch?

Thanks, very impressed with the software and its overall ease of use.

**Comment by n7tae** [comment]
Mvoice decodes either codec automatically regardless of what the VoiceOnly/Voice+Data Setting is at. This mvoice codec setting only affects your outgoing stream. I tested this just now to make sure it still works, and it does. I used two different movice clients, one on my laptop and the other on my desktop, with each connected to my test mrefd reflector.

I'm not sure what you were experiencing, but I don't think it had anything to do with your codec setting.

I'm going to close this. If you think there is still something there, you can reopen this, or open a new issue.
