### ISSUE TITLE
low audio quality?

### ISSUE THREAD

**Issue by sysgdc** [n7tae/mvoice#22]
I just built the latest mvoice ver 1.1.4 on Ubuntu 22.x = Linux Mint 21.1.  No problems. Builds clean. It works.

Note my audio playback using mvoice Echo Test is intelligible but pretty low quality compared to other voice software. I am using a quality Plantronics USB headset.  I am not sure if this is a limitation of Codec2?  I've built mvoice with USE44100 = true but that doesn't seem to make any difference.
(Echo Time=8.6s Vol=-3dB Clip=0%)

I don't consider the audio quality to be a big problem. I just don't have enough experience with m17 to know if there are parameters I can control to improve it or if that's 'normal'

73, Greg K1UH

**Comment by n7tae** [comment]
Codec2 should sound every bit as good as DStar or DMR, maybe even a bit better.

The README should say that you want `Clip=0%` clipping and a  **`Vol=-14dB`** -ish. Then adjust your receive volume for a comfortable level. Let me know if that sounds better and I'll change the README. I use an inexpensive audio plug over-the-ear JBL headset. It has no mic gain adjustment. I set the mic gain in the Ubuntu Sound config. Once I get the clipping and vol right, I turn the headset ear-cup volume all the way up and then adjust my listening volume with my Ubuntu sound configuration. Let me know if that sounds better and I'll change the README.

**Comment by n7tae** [comment]
I doubt if you need USE44100. That's for really old systems.

**Comment by sysgdc** [comment]
I cranked down my Ubuntu mixer microphone volume control to 58% (-14db) and
the quality seems to be slightly improved.
Echo Time=18.3s Vol=-16dB Clip=0%
Echo Time=13.7s Vol=-12dB Clip=0%

Echo Test playback audio seems nearly equal to ~DMR quality but voice still
sounds a bit synthetic to my ears, especially compared to wideband codecs
like G.7xx, VOIP, etc.

Conclusion: I think the latest Operating description in the README.md is
accurate.
Okay with me to close this issue.

PS:

Note there is a minor typo link error in README,
--> Building and installing the OpenDHT support
https://github./com/savoirfairelinux/opendht.git

Regards,

73, Greg K1UH
