### ISSUE TITLE
Click on "Settings dialogue" makes mvoice hang with 100% CPU

### ISSUE THREAD

**Issue by dd5xl** [n7tae/mvoice#4]
mvoice built on Lubuntu 18.04.5 LTS hangs with 100% CPU when "Settings" button is clicked in main window.
However, "Echo Test" and "Quit" work.

**Comment by n7tae** [comment]
Sorry, I don't have a computer I can install Lubuntu on, but I suspect Lubuntu can't support some gtkmm feature that the mvoice Settings dialog uses. There is nothing much I can do about that. You could try recompiling mvoice with gdb support, then starting it with gdb and when it locks up do a control-C and then a "bt" command to see where the program is when it froze.

Another option is to just add your callsign to the M17SourceCallsign='' line in the etc/mvoice.cfg file. Just put your capitalized callsign between single quotes. That should unlock your PTT toggle button.

**Comment by n7tae** [comment]
Sorry, you're right. I found a bug and pushed up a fix. If it works for you, please close this issue.

**Comment by n7tae** [comment]
nothing heard.
