### ISSUE TITLE
MVoice MS Windows version ?

### ISSUE THREAD

**Issue by sp2ong** [n7tae/mvoice#5]
There is interest in the M17 MVoice application but many people ask if there is a version for MS Windows :-). Many Digital Voice users are people who don't use Linux on a daily basis, so probably the MSWindows compiled version (as is the case with FreeDV) would increase the number of people who would test the M17. But doing cross-compile applications is not that simple.

**Comment by n7tae** [comment]
An M17 client is available from nostar, https://github.com/nostar/dudestar.
