### ISSUE TITLE
Audio quality M17

### ISSUE THREAD

**Issue by sp2ong** [n7tae/mvoice#6]
After a few days of testing using MVoice on the M17-POL and listening to the audio on the other reflectors, the audio quality on the M17 is worse than the audio on the DMR using the md380-emu software vocoder.

I wonder what the quality of audio depends on when using Codec2?

**Comment by n7tae** [comment]
I would suspect that if you are using Codec 2 3200 (M17 voice-only), audio quality will ultimately be limited by the quality of the microphone at the source and the quality of the speakers at the destination.

Please keep in mind that mvoice is a prototype application and as such, doesn't do any audio filtering of either the ALSA sound library pcm stream sent to the encoder or the output of the decoder sent to the ALSA sound library. Most digital radios have built in band-pass audio filter on both the microphone and the speaker to ensure that pcm streams are perfectly matched to their devices. Mvoice is not so sophisticated.

It is also possible I have made some error in my effort to translate David Rowe's codec to C++, but I doubt it. In my experience, subtle coding errors result in complete failure of the encoder and/or decoder.

I'm unclear about what actionable item is in this Issue. Are you doing a strict "apples-to-apples" comparison? Are you listening to the same audio source stream on your md380-emu and mvoice? Can you be more specific about the differences?

If you really want to discover the exact differences between mvoice and md380-emu, you can use my "c2-test" repo to build a freestanding encoder and decoder. The encoder will accept a raw pcm stream (mono, 8kHz, 16-bit, little-endian) and output encoded data. The decoder will accept encoded data and output a raw pcm stream. The "m17" branch will build a Codec 2 encoder and decoder that will only do 1600 and 3200 and is virtually identical to the vocoder used in mvoice. In this way, you can do a very scientific comparisons of Codec 2 and the md380-emu. If you find distinct differences between my implementation of Codec 2 and the md380-emu, I will be happy to entertain that comparison on my c2-test repo.

**Comment by sp2ong** [comment]
Thank you very much for your comprehensive answer.
We use the "Voice only" option My assessment of the quality difference between the audio on the M17 and the md380's DMR is not 1: 1 and not scientifically we only clearly hear the difference in sound quality and in the form of "distortion". It is difficult for me to describe it, sometimes I can hear that the sound has the effect of such "cat's meowing"  :-)
I understand that it is all in the testing stage and my comments are not a criticism of the M17, but I think that every remark can contribute to a better solution and we are very happy that there is an application like MVoice because it allows us to try to use M17 at this stage and this is valuable.

**Comment by sp2ong** [comment]
Tom,

After many tests of "Echo Test" in Mvoice, I noticed that the sound is not "hoarse" (or almost absent this effect) when speaking into the microphone holding it almost to the mouth, and then adjust the microphone GAIN. It seems that the audio system in MVoice is very sensitive to the level of background noise, and therefore when you speak practically at the mouth into the microphone, this noise does not have such an impact on the quality of coding it to Codec2.

73 Waldek SP2ONG
